syntax = "proto3";

option go_package = "github.com/karanveersp/job-runner/proto;jobrunner";

package job_runner;

// JobRunner is a remote job execution service.
service JobRunner {
    // Start takes a command and returns a job id.
    rpc Start(Command) returns (Job) {}

    // Stop takes a job id and returns an empty message or error. A User can only
    // stop jobs that they have started, while Admins can stop any job.
    rpc Stop(Job) returns (Empty) {}

    // List takes a job id and returns metadata.
    // Users only list a job that they have started, while Admins can list any job.
    rpc List(Job) returns (JobMetadata) {}

    // Monitor takes a job id and tails the output from the beginning. A User
    // can only monitor their jobs, while Admins can monitor any job.
    rpc Monitor(Job) returns (stream Output) {}
}

// Status models all job states
enum Status {
    PENDING = 0;
    RUNNING = 1;
    COMPLETED = 2;
    FAILED = 3;
    STOPPED = 4;
}

// Empty represents a unit or empty value
message Empty {}

// Command is a simple wrapper on the command string slice
message Command {
    repeated string cmd = 1; // includes program and arguments
}

// Job is a simple wrapper on the job's id string
message Job {
    int64 id = 1;  // assigned job id
}

// JobMetadata provides job info
message JobMetadata {
    Status status = 1;        // job status
    int32 exit_code = 2;      // job exit code
}

// Output is a wrapper on the []byte received from the server
message Output {
    bytes chunk = 1; // combined stdout and stderr output
}
